### ISSUE TITLE
dpkg-buildpackage -3 fails to create telegram in /usr/local/bin (cannot stat)

### ISSUE THREAD

**Issue by naryfa** [kenorb-contrib/tg#14]
Hi, I apologize if I sound too noob, but this is the problem I am having on Mint 19 with all deps satisfied:

a - objs/crypto/err_openssl.o
a - objs/crypto/err_altern.o
a - objs/auto/auto-skip.o
a - objs/auto/auto-fetch.o
a - objs/auto/auto-store.o
a - objs/auto/auto-autocomplete.o
a - objs/auto/auto-types.o
a - objs/auto/auto-fetch-ds.o
a - objs/auto/auto-free-ds.o
a - objs/auto/auto-store-ds.o
a - objs/auto/auto-print-ds.o
gcc objs/main.o objs/loop.o objs/interface.o objs/lua-tg.o objs/json-tg.o objs/python-tg.o objs/python-types.o libs/libtgl.a -Wl,-Bsymbolic-functions -Wl,-z,relro -L/usr/local/lib -L/usr/lib -L/usr/lib  -rdynamic -ggdb -levent -ljansson -lconfig -lz -lgcrypt -levent   -lreadline -llua5.2  -lm -ldl  -lpthread -lutil -ldl -o bin/telegram-cli
make[1]: Leaving directory '/home/mint/Downloads/tg'
   dh_auto_test
rm server.pub
 debian/rules binary
cp tg-server.pub server.pub
dh binary --with autotools-dev
dh: The autotools-dev sequence is deprecated and replaced by dh in debhelper (>= 9.20160115)
dh: This feature will be removed in compat 12.
   dh_testroot
   dh_prep
	rm -f -- debian/telegram-cli.substvars
	rm -fr -- debian/.debhelper/generated/telegram-cli/ debian/telegram-cli/ debian/tmp/
   dh_auto_install
	install -d debian/telegram-cli
	make -j1 install DESTDIR=/home/mint/Downloads/tg/debian/telegram-cli AM_UPDATE_INFO_DIR=no
make[1]: Entering directory '/home/mint/Downloads/tg'
install telegram /usr/local/bin
install: cannot stat 'telegram': No such file or directory
Makefile:69: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/home/mint/Downloads/tg'
dh_auto_install: make -j1 install DESTDIR=/home/mint/Downloads/tg/debian/telegram-cli AM_UPDATE_INFO_DIR=no returned exit code 2
debian/rules:17: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2

any ideas?

**Comment by berryamin** [comment]
Hi,
   please look at the 2 following lines:

The build process has compiled a "telegram-cli" binary as you see below with the "-o bin/telegram-cli"
<pre>
gcc objs/main.o objs/loop.o objs/interface.o objs/lua-tg.o objs/json-tg.o objs/python-tg.o objs/python-types.o libs/libtgl.a -Wl,-Bsymbolic-functions -Wl,-z,relro -L/usr/local/lib -L/usr/lib -L/usr/lib -rdynamic -ggdb -levent -ljansson -lconfig -lz -lgcrypt -levent -lreadline -llua5.2 -lm -ldl -lpthread -lutil -ldl -o bin/telegram-cli
</pre>

Now the install part looks for a "telegram" binary .. hence the 

<pre>
make[1]: Entering directory '/home/mint/Downloads/tg'
install telegram /usr/local/bin
 </pre>

Therefore, you get the error message;
"install: cannot stat 'telegram': No such file or directory"

**Comment by berryamin** [comment]
I hit the same issue when building on debian:buster .. Will try to check what's going on

**Comment by berryamin** [comment]
Currently working on a personnal branch to fix this issue
https://github.com/kenorb-contrib/tg/compare/master...berryamin:update-debian-packaging

**Comment by naryfa** [comment]
Terrific, thank you for such fast response and effort.

**Comment by berryamin** [comment]
I might open a Pull Request to fix the debian packaging issue, but more needs to be done on this, so it might take time.
Meanwhile, you may do the following to have the updated version:

<pre>
cd /tmp
git clone  https://github.com/kenorb-contrib/tg.git --depth 1
cd tg
git remote add berryamin   https://github.com/berryamin/tg.git
git fetch berryamin update-debian-packaging
git checkout  update-debian-packaging
</pre>

dpkg-buildpackage -b
ls -l /tmp/*deb

**Comment by naryfa** [comment]
I hate to break it but...  no, dpkg-buildpackage -b produces:

make[1]: Leaving directory '/tmp/tg'
   dh_auto_build
	make -j1
make[1]: Entering directory '/tmp/tg'
make[1]: *** No rule to make target 'tgl/scheme.tl', needed by 'auto/scheme.tl'.  Stop.
make[1]: Leaving directory '/tmp/tg'
dh_auto_build: make -j1 returned exit code 2
debian/rules:22: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

**Comment by berryamin** [comment]
Hmm my mistake, please use "--recursive" when performing the clone step. I've updated the previous post accordingly.

**Comment by naryfa** [comment]
OK, this time it progressed more, but it seems to have failed on signing, is that a problem?

make[1]: Leaving directory '/tmp/tg'
   dh_auto_build
	make -j1
make[1]: Entering directory '/tmp/tg'
make[1]: *** No rule to make target 'tgl/scheme.tl', needed by 'auto/scheme.tl'.  Stop.
make[1]: Leaving directory '/tmp/tg'
dh_auto_build: make -j1 returned exit code 2
debian/rules:22: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

**Comment by berryamin** [comment]
Signing issue does not seem to be a problem, I hit it also, but packages were built anyway.
But it seems that you still don't have the right content below tgl/ 
Please fix it with
cd /tmp/tg
git clone https://github.com/vysheng/tgl.git

**Comment by naryfa** [comment]
I've redone all the steps you mentioned, signing failed but it built the packages:

-rw-r--r-- 1 mint mint  846032 Mar 30 13:40 /tmp/telegram-cli_1.0.6-1_amd64.deb
-rw-r--r-- 1 mint mint 1861320 Mar 30 13:40 /tmp/telegram-cli-dbgsym_1.0.6-1_amd64.ddeb

Then I did:
sudo dpkg -i /tmp/*.deb

And it installed, but won't send me a code.

**Comment by berryamin** [comment]
Hmm looks strange, working great here..

**Comment by naryfa** [comment]
OK, I got it.

Thank you for all the help.

PS. My bad for not realizing the second .deb was for debug symbols, perhaps purposely named .ddeb for the time of need.

**Comment by berryamin** [comment]
#15
