### ISSUE TITLE
Problems connecting to servers?

### ISSUE THREAD

**Issue by thesnowdog** [kenorb-contrib/tg#23]
Compiled on Raspberry Pi 4 without any errors. When launched for first time, I get the following:

Telegram-cli uses libtgl version 2.1.0
Telegram-cli includes software developed by the OpenSSL Project
for use in the OpenSSL Toolkit. (http://www.openssl.org/)
I: config dir=[/home/pi/.telegram-cli]
[/home/pi/.telegram-cli] created
[/home/pi/.telegram-cli/downloads] created
 *** 1594086515.004194 public key 'tg-server.pub' loaded successfully
 *** 1594086515.004328 Couldn't open public key file: /etc/telegram-cli/server.pub
 *** 1594086515.004357 Can not load key /etc/telegram-cli/server.pub
 *** 1594086515.004487 public key 'tg-server.pub' loaded successfully
 *** 1594086515.004534 'direct' public key loaded successfully
 *** 1594086515.004685 DC1 '' update: 149.154.175.50:443
 *** 1594086515.004723 DC2 '' update: 149.154.167.51:443
 *** 1594086515.004748 DC3 '' update: 149.154.175.100:443
 *** 1594086515.004772 DC4 '' update: 149.154.167.91:443
 *** 1594086515.004811 DC5 '' update: 149.154.171.5:443
 *** 1594086515.004837 DC1 '' update: 2001:b28:f23d:f001::a:443
 *** 1594086515.004859 DC2 '' update: 2001:67c:4e8:f002::a:443
 *** 1594086515.004880 DC3 '' update: 2001:b28:f23d:f003::a:443
 *** 1594086515.004901 DC4 '' update: 2001:67c:4e8:f004::a:443
 *** 1594086515.004925 DC5 '' update: 2001:b28:f23f:f005::a:443
 *** 1594086515.238249 outbound rpc connection from dc #3 becomed ready
 *** 1594086515.241081 outbound rpc connection from dc #1 becomed ready
 *** 1594086516.759275 Sent query #6846549451330888704 of size 124 to DC 3
 *** 1594086516.979745 adjusting CLOCK_MONOTONIC delta to -0.218079
 *** 1594086516.979801 work_new_session_created: msg_id = 6846549456515509249, dc = 3
 *** 1594086516.980106 DC1 '' update: 149.154.175.51:443
 *** 1594086516.980150 DC1 '' update: 2001:0b28:f23d:f001:0000:0000:0000:000a:443
 *** 1594086516.980221 DC2 '' update: 149.154.167.50:443
 *** 1594086516.980293 DC2 '' update: 149.154.167.151:443
 *** 1594086516.980363 DC2 '' update: 2001:067c:04e8:f002:0000:0000:0000:000a:443
 *** 1594086516.980445 DC2 '' update: 2001:067c:04e8:f002:0000:0000:0000:000b:443
 *** 1594086516.980516 DC3 '' update: 2001:0b28:f23d:f003:0000:0000:0000:000a:443
 *** 1594086516.980598 DC4 '' update: 149.154.167.92:443
 *** 1594086516.980668 DC4 '' update: 2001:067c:04e8:f004:0000:0000:0000:000a:443
 *** 1594086516.980737 DC4 '' update: 149.154.165.120:443
 *** 1594086516.980812 DC4 '' update: 2001:067c:04e8:f004:0000:0000:0000:000b:443
 *** 1594086516.980880 DC5 '' update: 2001:0b28:f23f:f005:0000:0000:0000:000a:443
 *** 1594086516.980949 DC5 '' update: 91.108.56.176:443
 *** 1594086517.465375 Sent query #6846549452335096832 of size 124 to DC 1
 *** 1594086517.590707 adjusting CLOCK_MONOTONIC delta to -1.079424
 *** 1594086517.590883 work_new_session_created: msg_id = 6846549459552909313, dc = 1
 *** 1594086547.265411 fail_connection: read_error Connection timed out
 *** 1594086547.265642 Lost connection to server... 149.154.171.5:80
 *** 1594086547.265948 fail_connection: read_error Connection timed out
 *** 1594086547.266119 Lost connection to server... 149.154.167.91:80
 *** 1594086547.266330 fail_connection: read_error Connection timed out
 *** 1594086547.266487 Lost connection to server... 149.154.167.51:80

And the connection problems continue after that. I am never prompted to enter my phone number.
Any ideas? I get no response when I ping these servers. But I am able to ping just about everything else on the internet just fine.

**Comment by Paulchen232** [comment]
I can ping the server 149.154.167.51. Perhaps it go now.

**Comment by thesnowdog** [comment]
The client is now working perfectly. Weird...
For awhile, I thought my ISP had blocked Telegram. I did see posts on Reddit to that effect.

Thanks anyway.
