### ISSUE TITLE
No such file exists

### ISSUE THREAD

**Issue by sammydangers** [kenorb-contrib/tg#32]
git clone --recursive
                         │ https://github.com/CHAN
                         │GETHIS/tg.git && cd tg
                         │-bash: ​ git clone --recu
                         │rsive https://github.com
                         │/CHANGETHIS/tg.git : No
                         │such file or directory
                         │$

**Comment by Paulchen232** [comment]
Perhaps you want to know that you musst change CHANGETHIS in  kenorb-contrib

**Comment by sammydangers** [comment]
I clearly was doing to much at once to miss that. Thanks
