### ISSUE TITLE
API_64BIT_LOGIN_APP_OUTDATED_46:

### ISSUE THREAD

**Issue by Paulchen232** [kenorb-contrib/tg#52]
Is it possible repair this:
if I wont login this is going on:
`*** 1638591946.457996 Notification API_64BIT_LOGIN_APP_OUTDATED_46: You are using an outdated app that is no longer supported. To access your messages, please update your app to the latest version.
 *** 1638591946.466778 Incorrect phone number`
The login is going away.

**Comment by GeoIH** [comment]
Hey, Paulchen232, you could solve it?

**Comment by Paulchen232** [comment]
No, I have only see that it so often ask.

**Comment by abitmore** [comment]
Yes, this a duplicate of #51. And #53 too.
