### ISSUE TITLE
How to get <msg-id>

### ISSUE THREAD

**Issue by changxiangzhong** [kenorb-contrib/tg#56]
I'm trying to reply an message to an existing message. According to the help menu, I need <msg-id> to specify which one to reply. Where can I find those <msg-id>?

**Comment by Paulchen232** [comment]
With the argument `-N`

**Comment by changxiangzhong** [comment]
@Paulchen232, could you be more specific?  How can I get msg-id?
`> history @aassuutt -n
FAIL: 38: too many args #3
`

**Comment by changxiangzhong** [comment]
Ah! Found it! `bin/telegram-cli -N`. Thanks a lot!
