### ISSUE TITLE
How  do I view a File/Video/image

### ISSUE THREAD

**Issue by jaitra1264** [kenorb-contrib/tg#57]
How do I view files sent in chat?

**Comment by Paulchen232** [comment]
IIf you use a full Operatimg System use the Telegram CLI Argument `-W` and the command view_photo.

**Comment by jaitra1264** [comment]
can you tell me exact syntax to view a photo?

**Comment by jaitra1264** [comment]
Can you tell me the exact syntax to view image? I can't get it working properly

**Comment by Paulchen232** [comment]
This is from the `help` command:
`view_photo <msg-id>` Downloads file to downloads dirs. Then tries to open it with system default action.
So I think if you use `-W` you see the msg-Id. Then use `view_photo <msg-id>`.

**Comment by jaitra1264** [comment]
ahh no problem, it works now but it seems to be stuck at [0%Down]
